import placeholderOne from "./Images/placeholderOne.jpg"

export const challengesData = [
    {
        id: 1,
        img: placeholderOne,
        alt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
    {
        id: 2,
        img: placeholderOne,
        alt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
    {
        id: 3,
        img: placeholderOne,
        imgAlt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
    {
        id: 4,
        img: placeholderOne,
        alt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
    {
        id: 5,
        img: placeholderOne,
        alt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
    {
        id: 6,
        img: placeholderOne,
        alt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
    {
        id: 7,
        img: placeholderOne,
        imgAlt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
    {
        id: 8,
        img: placeholderOne,
        alt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
];