export const challengesData = [
    {
        id: 1,
        img: "Screenshot",
        alt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
    {
        id: 2,
        img: "Screenshot",
        alt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
    {
        id: 3,
        img: "Screenshot",
        imgAlt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
    {
        id: 4,
        img: "Screenshot",
        alt: "Image description",
        designIcon: "design Icon here",
        designIconAlt: "Design Icon alt",
        codeIcon: "design Icon here",
        codeIconAlt: "code Icon alt",
        title: "Admin Dashboard",
        link: "the codepen repo",
    },
];